name: Deploy to Nekoweb

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Prepare build
#         run: |
#           mkdir -p ./build
#           rsync -av --exclude='images/' --exclude='shrines/images/' ./public/ ./build/

#       - name: Deploy to Nekoweb
#         uses: mp-pinheiro/nekoweb-deploy@main
#         with:
#           API_KEY:
#           BUILD_DIR: "./build"
#           DEPLOY_DIR: "/angs-corner.nekoweb.org"
#           CLEANUP: "False"
#           DELAY: ".5"
#           NEKOWEB_PAGENAME: "angs-corner"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # your build step here

      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: "angs-corner.nekoweb.org"
          nekoweb-username: "angs-corner"
          directory: "public"
